# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d301477a375c143edf712f9f6af9be598a860aa2a894afacc3301333eb35a934a971e65e099e1ad22bcc26ceae5648d775ded29949e65f68ac090505be2c238

test:
  secret_key_base: 95a1c5ca430a5d55b62967e28c8b4d26d030dbface818befeca13446a3146274faa52164616cf89ea8017b1c0b75976b9016f120ebd34ea9eb0ca8e173dabe59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
